# config.toml
# https://github.com/CrimsonRay/slender

baseurl = "https://shablag.com/"
languageCode = "en-us"
title = "#!blag"
MetaDataFormat = "toml"
theme = "slim"
paginate = 10
PaginatePath = "/"

[author]
    name = "Shammah Chancellor"

[permalinks]

    # Permalink format for pages.
    page = "/:title/"

    # Permalink format for blog posts.
    post = "/article/:title/"

[params]

    # Change the color scheme of Slender.
    # See above for preview and list of color schemes.
    colorscheme = "white"

    # Tagline; HTML accepted here. Keep it concise.
    tagline = "Saving the world one quip at a time"

    # Footer; Markdown accepted here.
    footer = "Copyright 2015 &copy; Shammah Chancellor"

    # Description and keywords for <meta> tags.
    # Remember to set this for your main page.
    # This will be overridden by whatever is set by the page or post,
    # defined by `description` and `keywords` variables in the front matter
    # of the markdown file.
    description = ""
    keywords = "default,page,keywords"

    # Social links, must be full URLs (e.g. https://github.com/CrimsonRay/).
    # Remove, comment, or leave blank any field to leave them out.
    #email = "mailto:your-email"
    github = "http://github.com/schancel"
    #bitbucket = "url-to-your-bitbucket"
    twitter = "https://twitter.com/micropresident"
    #stackoverflow = "url-to-your-stackoverflow"
    linkedin = "https://www.linkedin.com/in/schancellor"
    #facebook = "url-to-your-facebook"

    # Google Analytics
    # Remove, comment, or leave it blank if you don't have one.
    #ganalytics = "your-google-analytics-tracking-code"

[menu]

    # Menu for the nav bar.
    # There must always be one item present (e.g. home).
    [[menu.main]]
    identifier = "home"
    name       = "home"
    url        = "/"
    weight     = 0

    [[menu.main]]
    identifier = "about"
    name       = "about"
    url        = "/about/"
    weight     = 1
