# config.toml
# https://github.com/CrimsonRay/slender

baseurl = "https://shablag.com/"
languageCode = "en-us"
title = "#!blag"
MetaDataFormat = "toml"
theme = "slim"
paginate = 10
PaginatePath = "/"

[author]
    name = "Shammah Chancellor"

[permalinks]

    # Permalink format for pages.
    page = "/:title/"

    # Permalink format for blog posts.
    post = "/article/:title/"

[params]
    # Social links, must be full URLs (e.g. https://github.com/CrimsonRay/).
    # Remove, comment, or leave blank any field to leave them out.
    GithubID = "schancel"
    TwitterID = "micropresident"

    # Google Analytics
    # Remove, comment, or leave it blank if you don't have one.
    AnalyticsID = "UA-137279049-1"

    Summary = false

[menu]

    # Menu for the nav bar.
    # There must always be one item present (e.g. home).
    [[menu.main]]
    identifier = "home"
    name       = "home"
    url        = "/"
    weight     = 0

    [[menu.main]]
    identifier = "about"
    name       = "about"
    url        = "/about/"
    weight     = 1
